/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testFileLinterEmptyFile() {
        String path = "src/main/resources/emptyfile.js";
        List<String> expected = new ArrayList<>();
        assertEquals(expected, App.fileLinter(path));
    }

    @Test public void testFileLinterNoErrors() {
        String path = "src/main/resources/noerrors.js";
        List<String> expected = new ArrayList<>();
        assertEquals(expected, App.fileLinter(path));
    }

    @Test public void testFileLinterOneError() {
        String path = "src/main/resources/oneerror.js";
        List<String> expected = new ArrayList<>();
        expected.add("Line 8: Missing semicolon.");
        assertEquals(expected, App.fileLinter(path));
    }

    @Test public void testFileLinterFewErrors() {
        String path = "src/main/resources/fewerrors.js";
        assertEquals(4, App.fileLinter(path).toArray().length);
    }

    @Test public void testFileLinterManyErrors() {
        String path = "src/main/resources/gates.js";
        assertEquals(46, App.fileLinter(path).toArray().length);
    }
}
