/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Arrays;

public class Library {
    public static void main(String[] args) {
        int[] input = new int[]{1,7,2,9,7,3};
        System.out.println(containsDuplicates(input));
        int[] dice = roll(6);
        System.out.println(Arrays.toString(dice));
        System.out.println(calculateAverage(input));
    }

    public static int[] roll(int rollNumber) {
        int[] dice = new int[rollNumber];
        for(int i = 0; i < dice.length; i++) {
            dice[i] = (int) ((Math.random() * 6) + 1);
        }
        return dice;
    }

    public static boolean containsDuplicates(int[] input) {
        for(int i = 0; i<input.length; i++) {
            for(int j = 0; j<input.length; j++) {
                if(j != i && input[i] == input[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static float calculateAverage(int[] input) {
        float sum = 0;
        for(int i = 0; i < input.length; i++) {
            sum += input[i];
        }
        return sum/input.length;
    }
}
